apiVersion: v1
kind: ConfigMap
metadata:
  name: opensips-config
  namespace: opensips
data:
  opensips.cfg: |
    ####### Global Parameters #########
    log_level=3
    xlog_level=3
    syslog_enabled=yes
    syslog_facility=LOG_LOCAL0
    socket=udp:127.0.0.1:5060

    ####### Modules Section ########
    loadmodule "signaling.so"
    loadmodule "sl.so"
    loadmodule "tm.so"
    modparam("tm", "fr_timeout", 5)
    loadmodule "rr.so"
    modparam("rr", "append_fromtag", 0)
    loadmodule "maxfwd.so"
    loadmodule "sipmsgops.so"
    loadmodule "mi_fifo.so"
    modparam("mi_fifo", "fifo_name", "/run/opensips/opensips_fifo")
    modparam("mi_fifo", "fifo_mode", 0666)
    loadmodule "usrloc.so"
    modparam("usrloc", "nat_bflag", "NAT")
    modparam("usrloc", "working_mode_preset", "single-instance-no-db")
    loadmodule "registrar.so"
    modparam("registrar", "tcp_persistent_flag", "TCP_PERSISTENT")
    loadmodule "acc.so"
    modparam("acc", "early_media", 0)
    loadmodule "proto_udp.so"

    ####### Routing Logic ########
    route {
      if (!mf_process_maxfwd_header(10)) {
        send_reply(483,"Too Many Hops");
        exit;
      }

      if (is_method("INVITE")) {
        do_accounting("log");
      }
      
      if (!is_myself("$rd")) {
        route(relay);
      }
    }

    route[relay] {
      if (!t_relay()) {
        send_reply(500,"Internal Error");
      }
      exit;
    }
