apiVersion: apps/v1
kind: Deployment
metadata:
  name: opensips
  namespace: opensips
spec:
  replicas: 1
  selector:
    matchLabels:
      app: opensips
  template:
    metadata:
      labels:
        app: opensips
    spec:
      containers:
        - name: opensips
          image: opensips/opensips:latest
          ports:
            - containerPort: 5060
