apiVersion: v1
kind: Service
metadata:
  name: opensips
  namespace: opensips
spec:
  selector:
    app: opensips
  ports:
    - protocol: UDP
      port: 5060
      targetPort: 5060
  type: ClusterIP
